### ISSUE TITLE
Implement PubID parsing for PLATEAU

### ISSUE THREAD

**Issue by mico** [metanorma/pubid-plateau#1]
Document identifier parsing is currently implemented in https://github.com/relaton/relaton-plateau

Some identifiers examples:
- PLATEAU Handbook #00 第1.0版
- PLATEAU Handbook #09 第3.0版
- PLATEAU Technical Report #00

**Comment by mico** [comment]
@ronaldtse would you like to add anything?

**Comment by ronaldtse** [comment]
Look at the Relaton.org page on Plateau, gives you all you need 👍

**Comment by ronaldtse** [comment]
Maybe you can use GPT to even write this.

**Comment by mico** [comment]
@ronaldtse @andrew2net there are identifiers I'm not sure how correctly to parse:
- `PLATEAU Handbook #03-1 第1.0版` - is it correct that "-1" here is annex?
- `PLATEAU Technical Report #46_1`
- `PLATEAU Technical Report #46_2` - what is "_1" and "_2" here?
- `PLATEAU Handbook #11 第1.0版（民間活用編）`
- `PLATEAU Handbook #11 第1.0版（公共活用編）`

What to do with `（民間活用編）` and `（公共活用編）`. The literal meaning through Google Translate: edition for "private" or "public" use. But only two identifiers have these, others don't. Does it mean by default all documents have edition for public use? `（公共活用編）`

**Comment by ronaldtse** [comment]
When can we get this done? This has been forever...

> * `PLATEAU Handbook #03-1 第1.0版` - is it correct that "-1" here is annex?

Yes. `-` means Annex if it is a Handbook. This is the only Handbook Annex.

> * `PLATEAU Technical Report #46_1`
> * `PLATEAU Technical Report #46_2` - what is "_1" and "_2" here?

See: https://www.mlit.go.jp/plateau/file/libraries/doc/plateau_tech_doc_0046_1_ver01.pdf

Actually these should be:

* `PLATEAU Technical Report #46-1`
* `PLATEAU Technical Report #46-2`

These are "parts".

> * `PLATEAU Handbook #11 第1.0版（民間活用編）`
> * `PLATEAU Handbook #11 第1.0版（公共活用編）`
> 
> What to do with `（民間活用編）` and `（公共活用編）`.

Let's treat this as "part distinguishing description". i.e. consider the content inside parentheses like `民間活用編` as part numbers.
